---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-iber
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: bmcAdm1n
        image: juananmora/mysql
        imagePullPolicy: ""
        name: mysqlcompose
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage-iber
          mountPath: /var/lib/mysql
        resources: {}
      hostname: mysql
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mysql-persistent-storage-iber
        persistentVolumeClaim:
          claimName: mysql-pv-claim-iber
status: {}
