apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  ports:
  - name: "tcp-pre"
    port: 3306
    targetPort: 3306
  volumeMounts:
        - name: mysql-persistent-storage-iber
          mountPath: /var/lib/mysql
  selector:
    io.kompose.service: mysql
  type: LoadBalancer
  volumes:
      - name: mysql-persistent-storage-iber
        persistentVolumeClaim:
          claimName: mysql-pv-claim-iber
status:
  loadBalancer: {}
