apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: "http-pre"
    port: 8091
    targetPort: 8080
  selector:
    io.kompose.service: web
  type: LoadBalancer
status:
  loadBalancer: {}
